7667=res/drawable/ic_launcher_background_simple.xml
7668=res/drawable/ic_launcher_simple_foreground.xml
7669=res/drawable/ic_microphone.xml
7670=res/drawable/ic_shortcut_settings.xml
7671=res/drawable/ic_shortcut_voice_floating.xml
7672=res/drawable/ic_voice_assistant_widget_preview.xml
7673=res/drawable/toolpkg_widget_preview.xml
7674=res/layout/view_background_texture_player.xml
7675=res/mipmap-anydpi-v26/ic_launcher_simple.xml
7676=res/mipmap-anydpi-v26/ic_launcher_simple_round.xml
7677=res/xml/accessibility_service_config.xml
7678=res/xml/backup_rules.xml
7679=res/xml/data_extraction_rules.xml
7680=res/xml/file_paths.xml
7681=res/xml/interaction_service.xml
7682=res/xml/locales_config.xml
7683=res/xml/network_security_config.xml
7684=res/xml/shortcuts.xml
7685=res/xml/toolpkg_desktop_widget_info.xml
7686=res/xml/voice_assistant_widget_info.xml
